import type { TelegramGender, TelegramNameLocale } from '@shared-types';

const RU_MALE = [
  'Александр',
  'Алексей',
  'Андрей',
  'Антон',
  'Артём',
  'Борис',
  'Вадим',
  'Валентин',
  'Валерий',
  'Василий',
  'Виктор',
  'Виталий',
  'Владимир',
  'Владислав',
  'Вячеслав',
  'Геннадий',
  'Георгий',
  'Григорий',
  'Даниил',
  'Денис',
  'Дмитрий',
  'Евгений',
  'Егор',
  'Иван',
  'Игорь',
  'Илья',
  'Кирилл',
  'Константин',
  'Лев',
  'Леонид',
  'Максим',
  'Марк',
  'Матвей',
  'Михаил',
  'Никита',
  'Николай',
  'Олег',
  'Павел',
  'Пётр',
  'Роман',
  'Руслан',
  'Сергей',
  'Станислав',
  'Степан',
  'Тимофей',
  'Тимур',
  'Фёдор',
  'Эдуард',
  'Юрий',
  'Ярослав',
] as const;

const RU_FEMALE = [
  'Алина',
  'Алла',
  'Анастасия',
  'Ангелина',
  'Анна',
  'Валентина',
  'Валерия',
  'Вера',
  'Вероника',
  'Виктория',
  'Галина',
  'Дарья',
  'Диана',
  'Ева',
  'Евгения',
  'Екатерина',
  'Елена',
  'Елизавета',
  'Жанна',
  'Зоя',
  'Инна',
  'Ирина',
  'Карина',
  'Кира',
  'Кристина',
  'Ксения',
  'Лариса',
  'Лидия',
  'Любовь',
  'Людмила',
  'Маргарита',
  'Марина',
  'Мария',
  'Милана',
  'Надежда',
  'Наталья',
  'Нина',
  'Оксана',
  'Ольга',
  'Полина',
  'Регина',
  'Светлана',
  'София',
  'Тамара',
  'Татьяна',
  'Ульяна',
  'Эльвира',
  'Юлия',
  'Яна',
  'Ярослава',
] as const;

/** Masculine forms. */
const RU_SURNAMES = [
  'Абрамов',
  'Андреев',
  'Антонов',
  'Афанасьев',
  'Баранов',
  'Белов',
  'Беляев',
  'Богданов',
  'Борисов',
  'Васильев',
  'Виноградов',
  'Волков',
  'Воробьёв',
  'Гаврилов',
  'Голубев',
  'Гончаров',
  'Григорьев',
  'Гусев',
  'Давыдов',
  'Данилов',
  'Дмитриев',
  'Егоров',
  'Ефимов',
  'Жуков',
  'Журавлёв',
  'Зайцев',
  'Иванов',
  'Игнатьев',
  'Ильин',
  'Казаков',
  'Калинин',
  'Карпов',
  'Ковалёв',
  'Козлов',
  'Комаров',
  'Королёв',
  'Крылов',
  'Кудрявцев',
  'Кузнецов',
  'Кузьмин',
  'Лебедев',
  'Макаров',
  'Максимов',
  'Медведев',
  'Мельников',
  'Морозов',
  'Никитин',
  'Новиков',
  'Орлов',
  'Осипов',
  'Павлов',
  'Петров',
  'Поляков',
  'Попов',
  'Романов',
  'Сазонов',
  'Семёнов',
  'Сергеев',
  'Сидоров',
  'Смирнов',
  'Соколов',
  'Соловьёв',
  'Сорокин',
  'Степанов',
  'Тарасов',
  'Тимофеев',
  'Титов',
  'Фёдоров',
  'Филиппов',
  'Фомин',
  'Фролов',
  'Шестаков',
  'Щербаков',
  'Юдин',
  'Яковлев',
] as const;

const EN_MALE = [
  'Adam',
  'Alex',
  'Andrew',
  'Anthony',
  'Austin',
  'Brandon',
  'Brian',
  'Caleb',
  'Cameron',
  'Charles',
  'Chris',
  'Daniel',
  'David',
  'Dylan',
  'Eric',
  'Ethan',
  'Evan',
  'Gabriel',
  'Henry',
  'Ian',
  'Jack',
  'Jacob',
  'James',
  'Jason',
  'Jeremy',
  'John',
  'Jordan',
  'Joseph',
  'Justin',
  'Kevin',
  'Liam',
  'Logan',
  'Lucas',
  'Mark',
  'Mason',
  'Matthew',
  'Michael',
  'Nathan',
  'Nicholas',
  'Noah',
  'Oliver',
  'Owen',
  'Patrick',
  'Paul',
  'Peter',
  'Ryan',
  'Samuel',
  'Sean',
  'Thomas',
  'Tyler',
] as const;

const EN_FEMALE = [
  'Abigail',
  'Alexis',
  'Alice',
  'Amanda',
  'Amber',
  'Amelia',
  'Andrea',
  'Angela',
  'Anna',
  'Ashley',
  'Aubrey',
  'Audrey',
  'Ava',
  'Bella',
  'Brooke',
  'Chloe',
  'Claire',
  'Danielle',
  'Elena',
  'Ella',
  'Ellie',
  'Emily',
  'Emma',
  'Erica',
  'Grace',
  'Hannah',
  'Harper',
  'Hayley',
  'Isabella',
  'Jasmine',
  'Jenna',
  'Jessica',
  'Julia',
  'Kayla',
  'Kelly',
  'Lauren',
  'Layla',
  'Lily',
  'Lucy',
  'Madison',
  'Maya',
  'Megan',
  'Mia',
  'Natalie',
  'Nicole',
  'Olivia',
  'Paige',
  'Rachel',
  'Samantha',
  'Sophia',
] as const;

const EN_SURNAMES = [
  'Adams',
  'Allen',
  'Anderson',
  'Bailey',
  'Baker',
  'Bell',
  'Bennett',
  'Brooks',
  'Brown',
  'Campbell',
  'Carter',
  'Clark',
  'Coleman',
  'Collins',
  'Cook',
  'Cooper',
  'Davis',
  'Edwards',
  'Evans',
  'Fisher',
  'Foster',
  'Garcia',
  'Gray',
  'Green',
  'Griffin',
  'Hall',
  'Harris',
  'Hayes',
  'Henderson',
  'Hill',
  'Howard',
  'Hughes',
  'Jackson',
  'James',
  'Jenkins',
  'Johnson',
  'Jones',
  'Kelly',
  'King',
  'Lee',
  'Lewis',
  'Long',
  'Martin',
  'Miller',
  'Mitchell',
  'Moore',
  'Morgan',
  'Morris',
  'Murphy',
  'Nelson',
  'Parker',
  'Perry',
  'Peterson',
  'Phillips',
  'Powell',
  'Price',
  'Reed',
  'Richardson',
  'Roberts',
  'Robinson',
  'Rogers',
  'Ross',
  'Russell',
  'Sanders',
  'Scott',
  'Simmons',
  'Smith',
  'Stewart',
  'Taylor',
  'Thompson',
  'Turner',
  'Walker',
  'Ward',
  'Watson',
  'White',
  'Williams',
  'Wilson',
  'Wood',
  'Wright',
  'Young',
] as const;

/** Bios, kept under Telegram's 70-character limit and free of any verb that would give the sentence a gender. */
const RU_BIOS = [
  'Кофе, книги, горы',
  'Живу здесь и сейчас',
  'Фотографирую всё подряд',
  'Музыка громче слов',
  'Путешествия и хорошая музыка',
  'Читаю больше, чем пишу',
  'Спорт, море, книги',
  'Собираю виниловые пластинки',
  'Учу английский',
  'Готовлю по выходным',
  'Бег по утрам',
  'Люблю тишину',
  'В поисках хорошего кофе',
  'Горы лучше пляжа',
  'Фотография — это хобби',
  'Слушаю больше, чем говорю',
  'Дизайн и котики',
  'Мечтаю о море',
  'Работаю, путешествую, отдыхаю',
  'Просто хороший человек',
  'Пусть будет проще',
  'Чай вместо кофе',
  'Делаю вещи',
  'Всегда где-то ещё',
] as const;

const EN_BIOS = [
  'Coffee, books, mountains',
  'Living in the moment',
  'Photographer at heart',
  'Music louder than words',
  'Travel and good music',
  'Reading more than writing',
  'Sports, sea, books',
  'Collecting vinyl records',
  'Learning something new every day',
  'Weekend cook',
  'Morning runs',
  'In love with quiet',
  'In search of good coffee',
  'Mountains over beaches',
  'Photography is the hobby',
  'Listening more than talking',
  'Design and cats',
  'Dreaming of the ocean',
  'Work, travel, repeat',
  'Just a good human',
  'Keep it simple',
  'Tea, not coffee',
  'Making things',
  'Always somewhere else',
] as const;

const pick = <T>(list: readonly T[]): T =>
  list[Math.floor(Math.random() * list.length)] as unknown as T;

const coin = (): boolean => Math.random() < 0.5;

export type ConcreteGender = 'male' | 'female';
export type ConcreteLocale = 'ru' | 'en';

export interface GeneratedName {
  readonly firstName: string;
  readonly lastName: string;
  readonly gender: ConcreteGender;
  readonly locale: ConcreteLocale;
}

const resolveGender = (gender: TelegramGender): ConcreteGender =>
  gender === 'mixed' ? (coin() ? 'male' : 'female') : gender;

const resolveLocale = (locale: TelegramNameLocale): ConcreteLocale =>
  locale === 'mixed' ? (coin() ? 'ru' : 'en') : locale;

const oneName = (gender: ConcreteGender, locale: ConcreteLocale): GeneratedName => {
  if (locale === 'ru') {
    const surname = pick(RU_SURNAMES);
    return {
      firstName: pick(gender === 'male' ? RU_MALE : RU_FEMALE),
      lastName: gender === 'female' ? `${surname}а` : surname,
      gender,
      locale,
    };
  }
  return {
    firstName: pick(gender === 'male' ? EN_MALE : EN_FEMALE),
    lastName: pick(EN_SURNAMES),
    gender,
    locale,
  };
};

/** Attempts before a repeat is accepted. */
const UNIQUE_TRIES = 24;

/** One run's worth of names. */
export class NameGenerator {
  private readonly used = new Set<string>();

  constructor(
    private readonly gender: TelegramGender,
    private readonly locale: TelegramNameLocale,
  ) {}

  next(): GeneratedName {
    for (let i = 0; i < UNIQUE_TRIES; i += 1) {
      const name = oneName(resolveGender(this.gender), resolveLocale(this.locale));
      const key = `${name.firstName} ${name.lastName}`;
      if (!this.used.has(key)) {
        this.used.add(key);
        return name;
      }
    }
    return oneName(resolveGender(this.gender), resolveLocale(this.locale));
  }
}

/** Telegram's own cap. */
export const BIO_MAX = 70;

export const generateBio = (locale: ConcreteLocale): string =>
  pick(locale === 'ru' ? RU_BIOS : EN_BIOS);
